mysql:
  user: "root"              # MySQL 用户名
  password: ""      # MySQL 密码
  host: "mysql"         # MySQL 主机地址
  port: 3306                # MySQL 端口
  database: "my_database"   # MySQL 数据库名称

clickhouse:
  host: "clickhouse"         # ClickHouse 主机地址
  port: 9000                # ClickHouse 端口

prometheus:
  host: "prometheus"  # Prometheus的主机地址
  port: 9091            # Prometheus的端口号
  job: "random"         # Job名称，可根据需要配置

rabbitmq:
  url: "amqp://guest:guest@server_rabbitmq:5672/"
  exchange: "my_exchange"
  task_queue: "task_queue"
  result_queue: "result_queue"
  task_routing_key: "task_routing_key"
  result_routing_key: "result_routing_key"


log_file: "/root/logs/server.log" # 日志文件路径


